{% set name = "tailestim" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tailestim-{{ version }}.tar.gz
  sha256: 3b051609837907f49f2c411d7484aae4307af2592662b1f2620f61b4af17ddac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19

test:
  imports:
    - tailestim
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mu373/tailestim
  summary: A Python package for estimating tail parameters of heavy-tailed distributions, which is useful for analyzing power-law behavior in complex networks.
  dev_url: https://github.com/mu373/tailestim
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mu373
