{% set name = "tailestim" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tailestim-{{ version }}.tar.gz
  sha256: 708303a5bef8a39f5ea5be9dc9506298e0025d7717c30f73de86845c0986e9d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19

test:
  imports:
    - tailestim
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mu373/tailestim
  summary: A Python package for estimating tail parameters of heavy-tailed distributions, which is useful for analyzing power-law behavior in complex networks.
  dev_url: https://github.com/mu373/tailestim
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mu373
