{% set name = "tailestim" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tailestim-{{ version }}.tar.gz
  sha256: 14c92c195a546df692de92f1e6fce47012f23b17164f0ee75306e8cc08fb5ad6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - matplotlib
    - matplotlib-base >=3.5
    - python >={{ python_min }}
    - numpy >=1.19

test:
  imports:
    - tailestim
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://tailestim.readthedocs.io/
  summary: A Python package for estimating tail parameters of heavy-tailed distributions, which is useful for analyzing power-law behavior in complex networks.
  dev_url: https://github.com/mu373/tailestim
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mu373
